-- Set the database to SINGLE_USER mode
ALTER DATABASE AdventureWorks2014
SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
-- Try to rename the database
ALTER DATABASE AdventureWorks2014 MODIFY NAME = CtyABC2023
GO
-- Set the database to MULTI_USER mode
ALTER DATABASE CtyABC2023
SET MULTI_USER WITH ROLLBACK IMMEDIATE

--------------------------
ALTER DATABASE AWN_DW_Demo
SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
-- Try to rename the database
ALTER DATABASE AWN_DW_Demo MODIFY NAME = ABC_DW_Demo
GO
-- Set the database to MULTI_USER mode
ALTER DATABASE ABC_DW_Demo
SET MULTI_USER WITH ROLLBACK IMMEDIATE

--------------------------------
ALTER DATABASE AWN_STG_Demo
SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO
-- Try to rename the database
ALTER DATABASE AWN_STG_Demo MODIFY NAME = ABC_STG_Demo
GO
-- Set the database to MULTI_USER mode
ALTER DATABASE ABC_STG_Demo
SET MULTI_USER WITH ROLLBACK IMMEDIATE